[package]
repository = "https://github.com/clog-tool/clog-lib"
readme = "README.md"
keywords = ["git", "log", "changelog", "parser", "parse"]
license = "MIT"
name = "clog"
version = "0.8.2"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]
description = "A conventional changelog for the rest of us"
exclude = ["docs/*"]

[dependencies]
regex = "*"
toml = "*"
time = "*"

[dependencies.regex_macros]
version = "*"
optional = true

[features]
default = []

# For debugging output
debug = []

# for building with nightly and unstable features
# until regex_macros compiles with nightly again, this should be commented out
# unstable = ["regex_macros"]
unstable = []
